#!/usr/bin/env zsh

. ~/.dotfiles/environment.zsh

# oh-my-zsh options
HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
ZSH_THEME="spaceship"
plugins=(
  git
  ruby
  github
  httpie
  zsh-syntax-highlighting
  npm
)

if [ -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ] ; then
  plugins+=( zsh-autosuggestions )
fi

source $ZSH/oh-my-zsh.sh

# User configuration

if which chezmoi>/dev/null; then
  export DOTFILES=~/.dotfiles
  eval $(chezmoi completion zsh)
fi

alias cm=chezmoi
alias cma=chezmoi apply

function n () {
  ./node_modules/.bin/$1 "${@:2}"
}


alias be='bundle exec'
alias mongo_start='docker run -d -p 27017:27017 -p 28017:28017 -e AUTH=no tutum/mongodb:2.6'

export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
if which code >/dev/null; then
  export EDITOR=code
fi

#-tns-completion-
if [ -f ~/.tnsrc ]; then
  source ~/.tnsrc
fi

if [ -d ~/.fastlane/bin ] ; then
  export PATH="~/.fastlane/bin:$PATH"
fi

for f in ~/.dotfiles/**/config.zsh; do
  source $f
done

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

if [ -f ~/.fzf.zsh ]; then
  source ~/.fzf.zsh
fi
