#!/usr/bin/env zsh

export PATH="$PATH:/opt/homebrew/bin"

. ~/.dotfiles/environment.zsh

# oh-my-zsh options
HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"

plugins=(
  mise
  docker
  docker-compose
  git
  github
  heroku
  httpie
  npm
  rails
  ruby
  yarn
  z
  zsh-syntax-highlighting
)

if [ -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ] ; then
  plugins+=( zsh-autosuggestions )
fi

FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

source $ZSH/oh-my-zsh.sh

# User configuration

if which chezmoi>/dev/null; then
  export DOTFILES=~/.dotfiles
  eval $(chezmoi completion zsh)
fi

alias cm=chezmoi
alias cma="chezmoi apply && source ~/.zshrc"

if which code >/dev/null; then
  export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
fi

#-tns-completion-
if [ -f ~/.tnsrc ]; then
  source ~/.tnsrc
fi

if [ -d ~/.fastlane/bin ] ; then
  export PATH="~/.fastlane/bin:$PATH"
fi

for f in ~/.dotfiles/**/config.zsh; do
  source $f
done

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

if [ -f ~/.fzf.zsh ]; then
  source ~/.fzf.zsh
fi

[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

source ~/.dotfiles/completions.zsh

export PATH="./bin:$HOME/.local/bin:$PATH"

eval "$(starship init zsh)"
