#!/usr/bin/env zsh

source ~/.local/share/chezmoi/.helpers

install_nvm() {
  echo '▶️ Installing nvm'

  successfully curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

  echo '✅ Installed nvm'
}

if is_installed nvm; then
  echo '✅ nvm already installed'
else
  mkdir -p $NVM_DIR
  install_nvm
fi
