#!/usr/bin/env bash

source ~/.local/share/chezmoi/.helpers

install_asdf() {
  echo '▶️ Installing asdf'
  successfully git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.4
  echo '✅ Installed asdf'
}

install_plugins() {
  echo '▶️ Installing asdf plugins'
  asdf plugin-add ruby
  asdf plugin-add nodejs
  asdf plugin-add python
  asdf plugin-add kubectl 
  asdf plugin-add helm 

  # Install the nodejs gpg keyring to verify installs
  bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  echo '✅ Installed asdf plugins'
}

if is_installed asdf; then
  echo '✅ asdf already installed'
else
  successfully install_asdf
  install_plugins
fi
