disableStartupPopups: true
gui:
  showCommandLog: false
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
quitOnTopLevelReturn: true
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
