#!/usr/bin/env zsh

source ~/.local/share/chezmoi/.helpers

install_pyenv() {
  echo '▶️ Installing pyenv'

  successfully curl https://pyenv.run | bash

  echo '✅ Installed pyenv'
}

if is_installed pyenv; then
  echo '✅ pyenv is already installed'
else
  install_pyenv
fi

